### ISSUE TITLE
howto: define RsyncArgsExtra via more in backuppc_hosts

### ISSUE THREAD

**Issue by jardleex** [HanXHX/ansible-backuppc#9]
Hi,

I'd like to use $Conf{RsyncArgsExtra} in a hosts config.pl

```
backuppc_hosts:
- hostname: example.host
    state: present
    more:
      RsyncArgsExtra: [ '--bwlimit=60K' ]
```

But this leads to:

```
:~ tail -n 2 example.host.pl
# More options...
$Conf{RsyncArgsExtra} = [u'--bwlimit=60K'];
```

Understandable, BackupPC complains about the nice small _u_.
Here the link to the official documentation [documentation](http://backuppc.sourceforge.net/faq/BackupPC.html#_conf_rsyncargsextra_)

Can you give me a hint how to use the module in this case?

Thank you!

Best 
Jard
